# Question: What percent of people had a family member on the Titanic?

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       892 non-null    object
 1   1       892 non-null    object
 2   2       892 non-null    object
 3   3       892 non-null    object
 4   4       892 non-null    object
 5   5       715 non-null    object
 6   6       892 non-null    object
 7   7       892 non-null    object
 8   8       892 non-null    object
 9   9       892 non-null    object
 10  10      205 non-null    object
 11  11      890 non-null    object
dtypes: object(12)
memory usage: 83.8+ KB

In [23]:
import pandas as pd

df = pd.read_csv("titanic.csv", encoding='utf-8')
df = pd.read_csv("titanic.csv", header=None)
df.head(892)

,0,1,2,3,4,5,6,7,8,9,10,11
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,NaN,S
6,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S
8,8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.075,NaN,S
9,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,NaN,S
10,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,NaN,C
11,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,PP 9549,16.7,G6,S
12,12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.55,C103,S
13,13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,A/5. 2151,8.05,NaN,S
14,14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.275,NaN,S
15,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14,0,0,350406,7.8542,NaN,S
16,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55,0,0,248706,16,NaN,S
17,17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.125,NaN,Q
18,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13,NaN,S
19,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",female,31,1,0,345763,18,NaN,S
20,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.225,NaN,C
21,21,0,2,"Fynney, Mr. Joseph J",male,35,0,0,239865,26,NaN,S
22,22,1,2,"Beesley, Mr. Lawrence",male,34,0,0,248698,13,D56,S
23,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15,0,0,330923,8.0292,NaN,Q
24,24,1,1,"Sloper, Mr. William Thompson",male,28,0,0,113788,35.5,A6,S
25,25,0,3,"Palsson, Miss. Torborg Danira",female,8,3,1,349909,21.075,NaN,S
26,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)",female,38,1,5,347077,31.3875,NaN,S
27,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.225,NaN,C
28,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263,C23 C25 C27,S
29,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
30,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
31,31,0,1,"Uruchurtu, Don. Manuel E",male,40,0,0,PC 17601,27.7208,NaN,C
32,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
33,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.75,NaN,Q
34,34,0,2,"Wheadon, Mr. Edward H",male,66,0,0,C.A. 24579,10.5,NaN,S
35,35,0,1,"Meyer, Mr. Edgar Joseph",male,28,1,0,PC 17604,82.1708,NaN,C
36,36,0,1,"Holverson, Mr. Alexander Oskar",male,42,1,0,113789,52,NaN,S
37,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
38,38,0,3,"Cann, Mr. Ernest Charles",male,21,0,0,A./5. 2152,8.05,NaN,S
39,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18,2,0,345764,18,NaN,S
40,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14,1,0,2651,11.2417,NaN,C
41,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40,1,0,7546,9.475,NaN,S
42,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)",female,27,1,0,11668,21,NaN,S
43,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
44,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3,1,2,SC/Paris 2123,41.5792,NaN,C
45,45,1,3,"Devaney, Miss. Margaret Delia",female,19,0,0,330958,7.8792,NaN,Q
46,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.05,NaN,S
47,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5,NaN,Q
48,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.75,NaN,Q
49,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
50,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18,1,0,349237,17.8,NaN,S
51,51,0,3,"Panula, Master. Juha Niilo",male,7,4,1,3101295,39.6875,NaN,S
52,52,0,3,"Nosworthy, Mr. Richard Cater",male,21,0,0,A/4. 39886,7.8,NaN,S
53,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49,1,0,PC 17572,76.7292,D33,C
54,54,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)",female,29,1,0,2926,26,NaN,S
55,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65,0,1,113509,61.9792,B30,C
56,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5,C52,S
57,57,1,2,"Rugg, Miss. Emily",female,21,0,0,C.A. 31026,10.5,NaN,S
58,58,0,3,"Novel, Mr. Mansouer",male,28.5,0,0,2697,7.2292,NaN,C
59,59,1,2,"West, Miss. Constance Mirium",female,5,1,2,C.A. 34651,27.75,NaN,S
60,60,0,3,"Goodwin, Master. William Frederick",male,11,5,2,CA 2144,46.9,NaN,S
61,61,0,3,"Sirayanian, Mr. Orsen",male,22,0,0,2669,7.2292,NaN,C
62,62,1,1,"Icard, Miss. Amelie",female,38,0,0,113572,80,B28,NaN
63,63,0,1,"Harris, Mr. Henry Birkhardt",male,45,1,0,36973,83.475,C83,S
64,64,0,3,"Skoog, Master. Harald",male,4,3,2,347088,27.9,NaN,S
65,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
66,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
67,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29,0,0,C.A. 29395,10.5,F33,S
68,68,0,3,"Crease, Mr. Ernest James",male,19,0,0,S.P. 3464,8.1583,NaN,S
69,69,1,3,"Andersson, Miss. Erna Alexandra",female,17,4,2,3101281,7.925,NaN,S
70,70,0,3,"Kink, Mr. Vincenz",male,26,2,0,315151,8.6625,NaN,S
71,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32,0,0,C.A. 33111,10.5,NaN,S
72,72,0,3,"Goodwin, Miss. Lillian Amy",female,16,5,2,CA 2144,46.9,NaN,S
73,73,0,2,"Hood, Mr. Ambrose Jr",male,21,0,0,S.O.C. 14879,73.5,NaN,S
74,74,0,3,"Chronopoulos, Mr. Apostolos",male,26,1,0,2680,14.4542,NaN,C
75,75,1,3,"Bing, Mr. Lee",male,32,0,0,1601,56.4958,NaN,S
76,76,0,3,"Moen, Mr. Sigurd Hansen",male,25,0,0,348123,7.65,F G73,S
77,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S
78,78,0,3,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,374746,8.05,NaN,S
79,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29,NaN,S
80,80,1,3,"Dowdell, Miss. Elizabeth",female,30,0,0,364516,12.475,NaN,S
81,81,0,3,"Waelens, Mr. Achille",male,22,0,0,345767,9,NaN,S
82,82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29,0,0,345779,9.5,NaN,S
83,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
84,84,0,1,"Carrau, Mr. Francisco M",male,28,0,0,113059,47.1,NaN,S
85,85,1,2,"Ilett, Miss. Bertha",female,17,0,0,SO/C 14885,10.5,NaN,S
86,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)",female,33,3,0,3101278,15.85,NaN,S
87,87,0,3,"Ford, Mr. William Neal",male,16,1,3,W./C. 6608,34.375,NaN,S
88,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.05,NaN,S
89,89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263,C23 C25 C27,S
90,90,0,3,"Celotti, Mr. Francesco",male,24,0,0,343275,8.05,NaN,S
91,91,0,3,"Christmann, Mr. Emil",male,29,0,0,343276,8.05,NaN,S
92,92,0,3,"Andreasson, Mr. Paul Edvin",male,20,0,0,347466,7.8542,NaN,S
93,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46,1,0,W.E.P. 5734,61.175,E31,S
94,94,0,3,"Dean, Mr. Bertram Frank",male,26,1,2,C.A. 2315,20.575,NaN,S
95,95,0,3,"Coxon, Mr. Daniel",male,59,0,0,364500,7.25,NaN,S
96,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.05,NaN,S
97,97,0,1,"Goldschmidt, Mr. George B",male,71,0,0,PC 17754,34.6542,A5,C
98,98,1,1,"Greenfield, Mr. William Bertram",male,23,0,1,PC 17759,63.3583,D10 D12,C
99,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34,0,1,231919,23,NaN,S
100,100,0,2,"Kantor, Mr. Sinai",male,34,1,0,244367,26,NaN,S
101,101,0,3,"Petranec, Miss. Matilda",female,28,0,0,349245,7.8958,NaN,S
102,102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
103,103,0,1,"White, Mr. Richard Frasar",male,21,0,1,35281,77.2875,D26,S
104,104,0,3,"Johansson, Mr. Gustaf Joel",male,33,0,0,7540,8.6542,NaN,S
105,105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37,2,0,3101276,7.925,NaN,S
106,106,0,3,"Mionoff, Mr. Stoytcho",male,28,0,0,349207,7.8958,NaN,S
107,107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21,0,0,343120,7.65,NaN,S
108,108,1,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.775,NaN,S
109,109,0,3,"Rekic, Mr. Tido",male,38,0,0,349249,7.8958,NaN,S
110,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.15,NaN,Q
111,111,0,1,"Porter, Mr. Walter Chamberlain",male,47,0,0,110465,52,C110,S
112,112,0,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C
113,113,0,3,"Barton, Mr. David John",male,22,0,0,324669,8.05,NaN,S
114,114,0,3,"Jussila, Miss. Katriina",female,20,1,0,4136,9.825,NaN,S
115,115,0,3,"Attalah, Miss. Malake",female,17,0,0,2627,14.4583,NaN,C
116,116,0,3,"Pekoniemi, Mr. Edvard",male,21,0,0,STON/O 2. 3101294,7.925,NaN,S
117,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.75,NaN,Q
118,118,0,2,"Turpin, Mr. William John Robert",male,29,1,0,11668,21,NaN,S
119,119,0,1,"Baxter, Mr. Quigg Edmond",male,24,0,1,PC 17558,247.5208,B58 B60,C
120,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2,4,2,347082,31.275,NaN,S
121,121,0,2,"Hickman, Mr. Stanley George",male,21,2,0,S.O.C. 14879,73.5,NaN,S
122,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.05,NaN,S
123,123,0,2,"Nasser, Mr. Nicholas",male,32.5,1,0,237736,30.0708,NaN,C
124,124,1,2,"Webber, Miss. Susan",female,32.5,0,0,27267,13,E101,S
125,125,0,1,"White, Mr. Percival Wayland",male,54,0,1,35281,77.2875,D26,S
126,126,1,3,"Nicola-Yarred, Master. Elias",male,12,1,0,2651,11.2417,NaN,C
127,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.75,NaN,Q
128,128,1,3,"Madsen, Mr. Fridtjof Arne",male,24,0,0,C 17369,7.1417,NaN,S
129,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
130,130,0,3,"Ekstrom, Mr. Johan",male,45,0,0,347061,6.975,NaN,S
131,131,0,3,"Drazenoic, Mr. Jozef",male,33,0,0,349241,7.8958,NaN,C
132,132,0,3,"Coelho, Mr. Domingos Fernandeo",male,20,0,0,SOTON/O.Q. 3101307,7.05,NaN,S
133,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47,1,0,A/5. 3337,14.5,NaN,S
134,134,1,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29,1,0,228414,26,NaN,S
135,135,0,2,"Sobey, Mr. Samuel James Hayden",male,25,0,0,C.A. 29178,13,NaN,S
136,136,0,2,"Richard, Mr. Emile",male,23,0,0,SC/PARIS 2133,15.0458,NaN,C
137,137,1,1,"Newsom, Miss. Helen Monypeny",female,19,0,2,11752,26.2833,D47,S
138,138,0,1,"Futrelle, Mr. Jacques Heath",male,37,1,0,113803,53.1,C123,S
139,139,0,3,"Osen, Mr. Olaf Elon",male,16,0,0,7534,9.2167,NaN,S
140,140,0,1,"Giglio, Mr. Victor",male,24,0,0,PC 17593,79.2,B86,C
141,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
142,142,1,3,"Nysten, Miss. Anna Sofia",female,22,0,0,347081,7.75,NaN,S
143,143,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)",female,24,1,0,STON/O2. 3101279,15.85,NaN,S
144,144,0,3,"Burke, Mr. Jeremiah",male,19,0,0,365222,6.75,NaN,Q
145,145,0,2,"Andrew, Mr. Edgardo Samuel",male,18,0,0,231945,11.5,NaN,S
146,146,0,2,"Nicholls, Mr. Joseph Charles",male,19,1,1,C.A. 33112,36.75,NaN,S
147,147,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27,0,0,350043,7.7958,NaN,S
148,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9,2,2,W./C. 6608,34.375,NaN,S
149,149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.5,0,2,230080,26,F2,S
150,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42,0,0,244310,13,NaN,S
151,151,0,2,"Bateman, Rev. Robert James",male,51,0,0,S.O.P. 1166,12.525,NaN,S
152,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22,1,0,113776,66.6,C2,S
153,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.05,NaN,S
154,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5,NaN,S
155,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
156,156,0,1,"Williams, Mr. Charles Duane",male,51,0,1,PC 17597,61.3792,NaN,C
157,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16,0,0,35851,7.7333,NaN,Q
158,158,0,3,"Corn, Mr. Harry",male,30,0,0,SOTON/OQ 392090,8.05,NaN,S
159,159,0,3,"Smiljanic, Mr. Mile",male,NaN,0,0,315037,8.6625,NaN,S
160,160,0,3,"Sage, Master. Thomas Henry",male,NaN,8,2,CA. 2343,69.55,NaN,S
161,161,0,3,"Cribb, Mr. John Hatfield",male,44,0,1,371362,16.1,NaN,S
162,162,1,2,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Milne)",female,40,0,0,C.A. 33595,15.75,NaN,S
163,163,0,3,"Bengtsson, Mr. John Viktor",male,26,0,0,347068,7.775,NaN,S
164,164,0,3,"Calic, Mr. Jovo",male,17,0,0,315093,8.6625,NaN,S
165,165,0,3,"Panula, Master. Eino Viljami",male,1,4,1,3101295,39.6875,NaN,S
166,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9,0,2,363291,20.525,NaN,S
167,167,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,NaN,0,1,113505,55,E33,S
168,168,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45,1,4,347088,27.9,NaN,S
169,169,0,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.925,NaN,S
170,170,0,3,"Ling, Mr. Lee",male,28,0,0,1601,56.4958,NaN,S
171,171,0,1,"Van der hoef, Mr. Wyckoff",male,61,0,0,111240,33.5,B19,S
172,172,0,3,"Rice, Master. Arthur",male,4,4,1,382652,29.125,NaN,Q
173,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1,1,1,347742,11.1333,NaN,S
174,174,0,3,"Sivola, Mr. Antti Wilhelm",male,21,0,0,STON/O 2. 3101280,7.925,NaN,S
175,175,0,1,"Smith, Mr. James Clinch",male,56,0,0,17764,30.6958,A7,C
176,176,0,3,"Klasen, Mr. Klas Albin",male,18,1,1,350404,7.8542,NaN,S
177,177,0,3,"Lefebre, Master. Henry Forbes",male,NaN,3,1,4133,25.4667,NaN,S
178,178,0,1,"Isham, Miss. Ann Elizabeth",female,50,0,0,PC 17595,28.7125,C49,C
179,179,0,2,"Hale, Mr. Reginald",male,30,0,0,250653,13,NaN,S
180,180,0,3,"Leonard, Mr. Lionel",male,36,0,0,LINE,0,NaN,S
181,181,0,3,"Sage, Miss. Constance Gladys",female,NaN,8,2,CA. 2343,69.55,NaN,S
182,182,0,2,"Pernot, Mr. Rene",male,NaN,0,0,SC/PARIS 2131,15.05,NaN,C
183,183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9,4,2,347077,31.3875,NaN,S
184,184,1,2,"Becker, Master. Richard F",male,1,2,1,230136,39,F4,S
185,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4,0,2,315153,22.025,NaN,S
186,186,0,1,"Rood, Mr. Hugh Roscoe",male,NaN,0,0,113767,50,A32,S
187,187,1,3,"O'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,NaN,1,0,370365,15.5,NaN,Q
188,188,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45,0,0,111428,26.55,NaN,S
189,189,0,3,"Bourke, Mr. John",male,40,1,1,364849,15.5,NaN,Q
190,190,0,3,"Turcin, Mr. Stjepan",male,36,0,0,349247,7.8958,NaN,S
191,191,1,2,"Pinsky, Mrs. (Rosa)",female,32,0,0,234604,13,NaN,S
192,192,0,2,"Carbines, Mr. William",male,19,0,0,28424,13,NaN,S
193,193,1,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19,1,0,350046,7.8542,NaN,S
194,194,1,2,"Navratil, Master. Michel M",male,3,1,1,230080,26,F2,S
195,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44,0,0,PC 17610,27.7208,B4,C
196,196,1,1,"Lurette, Miss. Elise",female,58,0,0,PC 17569,146.5208,B80,C
197,197,0,3,"Mernagh, Mr. Robert",male,NaN,0,0,368703,7.75,NaN,Q
198,198,0,3,"Olsen, Mr. Karl Siegwart Andreas",male,42,0,1,4579,8.4042,NaN,S
199,199,1,3,"Madigan, Miss. Margaret ""Maggie""",female,NaN,0,0,370370,7.75,NaN,Q
200,200,0,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24,0,0,248747,13,NaN,S
201,201,0,3,"Vande Walle, Mr. Nestor Cyriel",male,28,0,0,345770,9.5,NaN,S
202,202,0,3,"Sage, Mr. Frederick",male,NaN,8,2,CA. 2343,69.55,NaN,S
203,203,0,3,"Johanson, Mr. Jakob Alfred",male,34,0,0,3101264,6.4958,NaN,S
204,204,0,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.225,NaN,C
205,205,1,3,"Cohen, Mr. Gurshon ""Gus""",male,18,0,0,A/5 3540,8.05,NaN,S
206,206,0,3,"Strom, Miss. Telma Matilda",female,2,0,1,347054,10.4625,G6,S
207,207,0,3,"Backstrom, Mr. Karl Alfred",male,32,1,0,3101278,15.85,NaN,S
208,208,1,3,"Albimona, Mr. Nassef Cassem",male,26,0,0,2699,18.7875,NaN,C
209,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16,0,0,367231,7.75,NaN,Q
210,210,1,1,"Blank, Mr. Henry",male,40,0,0,112277,31,A31,C
211,211,0,3,"Ali, Mr. Ahmed",male,24,0,0,SOTON/O.Q. 3101311,7.05,NaN,S
212,212,1,2,"Cameron, Miss. Clear Annie",female,35,0,0,F.C.C. 13528,21,NaN,S
213,213,0,3,"Perkin, Mr. John Henry",male,22,0,0,A/5 21174,7.25,NaN,S
214,214,0,2,"Givard, Mr. Hans Kristensen",male,30,0,0,250646,13,NaN,S
215,215,0,3,"Kiernan, Mr. Philip",male,NaN,1,0,367229,7.75,NaN,Q
216,216,1,1,"Newell, Miss. Madeleine",female,31,1,0,35273,113.275,D36,C
217,217,1,3,"Honkanen, Miss. Eliina",female,27,0,0,STON/O2. 3101283,7.925,NaN,S
218,218,0,2,"Jacobsohn, Mr. Sidney Samuel",male,42,1,0,243847,27,NaN,S
219,219,1,1,"Bazzani, Miss. Albina",female,32,0,0,11813,76.2917,D15,C
220,220,0,2,"Harris, Mr. Walter",male,30,0,0,W/C 14208,10.5,NaN,S
221,221,1,3,"Sunderland, Mr. Victor Francis",male,16,0,0,SOTON/OQ 392089,8.05,NaN,S
222,222,0,2,"Bracken, Mr. James H",male,27,0,0,220367,13,NaN,S
223,223,0,3,"Green, Mr. George Henry",male,51,0,0,21440,8.05,NaN,S
224,224,0,3,"Nenkoff, Mr. Christo",male,NaN,0,0,349234,7.8958,NaN,S
225,225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38,1,0,19943,90,C93,S
226,226,0,3,"Berglund, Mr. Karl Ivar Sven",male,22,0,0,PP 4348,9.35,NaN,S
227,227,1,2,"Mellors, Mr. William John",male,19,0,0,SW/PP 751,10.5,NaN,S
228,228,0,3,"Lovell, Mr. John Hall (""Henry"")",male,20.5,0,0,A/5 21173,7.25,NaN,S
229,229,0,2,"Fahlstrom, Mr. Arne Jonas",male,18,0,0,236171,13,NaN,S
230,230,0,3,"Lefebre, Miss. Mathilde",female,NaN,3,1,4133,25.4667,NaN,S
231,231,1,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",female,35,1,0,36973,83.475,C83,S
232,232,0,3,"Larsson, Mr. Bengt Edvin",male,29,0,0,347067,7.775,NaN,S
233,233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59,0,0,237442,13.5,NaN,S
234,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5,4,2,347077,31.3875,NaN,S
235,235,0,2,"Leyson, Mr. Robert William Norman",male,24,0,0,C.A. 29566,10.5,NaN,S
236,236,0,3,"Harknett, Miss. Alice Phoebe",female,NaN,0,0,W./C. 6609,7.55,NaN,S
237,237,0,2,"Hold, Mr. Stephen",male,44,1,0,26707,26,NaN,S
238,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8,0,2,C.A. 31921,26.25,NaN,S
239,239,0,2,"Pengelly, Mr. Frederick William",male,19,0,0,28665,10.5,NaN,S
240,240,0,2,"Hunt, Mr. George Henry",male,33,0,0,SCO/W 1585,12.275,NaN,S
241,241,0,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C
242,242,1,3,"Murphy, Miss. Katherine ""Kate""",female,NaN,1,0,367230,15.5,NaN,Q
243,243,0,2,"Coleridge, Mr. Reginald Charles",male,29,0,0,W./C. 14263,10.5,NaN,S
244,244,0,3,"Maenpaa, Mr. Matti Alexanteri",male,22,0,0,STON/O 2. 3101275,7.125,NaN,S
245,245,0,3,"Attalah, Mr. Sleiman",male,30,0,0,2694,7.225,NaN,C
246,246,0,1,"Minahan, Dr. William Edward",male,44,2,0,19928,90,C78,Q
247,247,0,3,"Lindahl, Miss. Agda Thorilda Viktoria",female,25,0,0,347071,7.775,NaN,S
248,248,1,2,"Hamalainen, Mrs. William (Anna)",female,24,0,2,250649,14.5,NaN,S
249,249,1,1,"Beckwith, Mr. Richard Leonard",male,37,1,1,11751,52.5542,D35,S
250,250,0,2,"Carter, Rev. Ernest Courtenay",male,54,1,0,244252,26,NaN,S
251,251,0,3,"Reed, Mr. James George",male,NaN,0,0,362316,7.25,NaN,S
252,252,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29,1,1,347054,10.4625,G6,S
253,253,0,1,"Stead, Mr. William Thomas",male,62,0,0,113514,26.55,C87,S
254,254,0,3,"Lobb, Mr. William Arthur",male,30,1,0,A/5. 3336,16.1,NaN,S
255,255,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41,0,2,370129,20.2125,NaN,S
256,256,1,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29,0,2,2650,15.2458,NaN,C
257,257,1,1,"Thorne, Mrs. Gertrude Maybelle",female,NaN,0,0,PC 17585,79.2,NaN,C
258,258,1,1,"Cherry, Miss. Gladys",female,30,0,0,110152,86.5,B77,S
259,259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,NaN,C
260,260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50,0,1,230433,26,NaN,S
261,261,0,3,"Smith, Mr. Thomas",male,NaN,0,0,384461,7.75,NaN,Q
262,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3,4,2,347077,31.3875,NaN,S
263,263,0,1,"Taussig, Mr. Emil",male,52,1,1,110413,79.65,E67,S
264,264,0,1,"Harrison, Mr. William",male,40,0,0,112059,0,B94,S
265,265,0,3,"Henry, Miss. Delia",female,NaN,0,0,382649,7.75,NaN,Q
266,266,0,2,"Reeves, Mr. David",male,36,0,0,C.A. 17248,10.5,NaN,S
267,267,0,3,"Panula, Mr. Ernesti Arvid",male,16,4,1,3101295,39.6875,NaN,S
268,268,1,3,"Persson, Mr. Ernst Ulrik",male,25,1,0,347083,7.775,NaN,S

In [15]:
df.iloc[6]

0                    6
1                    0
2                    3
3     Moran, Mr. James
4                 male
5                  NaN
6                    0
7                    0
8               330877
9               8.4583
10                 NaN
11                   Q
Name: 6, dtype: object

AttributeError: Can only use .str accessor with string values!

In [24]:
df.iloc[6]

0                    6
1                    0
2                    3
3     Moran, Mr. James
4                 male
5                  NaN
6                    0
7                    0
8               330877
9               8.4583
10                 NaN
11                   Q
Name: 6, dtype: object

In [27]:
df(df("Embarked"] == 'Q'

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (371874306.py, line 1)